[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = '0.8.29'
via_ir = true
optimizer = true
optimizer_runs = 20_000

[profile.ci]
verbosity = 4

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin/contracts/",
    "erc4626-tests/=lib/openzeppelin/lib/erc4626-tests/",
    "forge-std/=lib/forge-std/src/",
    "halmos-cheatcodes/=lib/openzeppelin/lib/halmos-cheatcodes/src/",
    "openzeppelin/=lib/openzeppelin/",
    "openzeppelin-v4/=lib/openzeppelin-v4",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
