[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = '0.8.26'
via_ir = true

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin/contracts/",
    "erc4626-tests/=lib/openzeppelin/lib/erc4626-tests/",
    "forge-std/=lib/forge-std/src/",
    "halmos-cheatcodes/=lib/openzeppelin/lib/halmos-cheatcodes/src/",
    "openzeppelin/=lib/openzeppelin/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
